### ISSUE TITLE
导入中文text无法运行

### ISSUE THREAD

**Issue by Sweetjy** [jiesutd/YEDDA#37]
event:  A
Command:a
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\python\Anaconda\envs\tenvf\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "D:/python/workspace/YEDDA-master/YEDDA.py", line 313, in textReturnEnter
    self.executeCursorCommand(press_key.lower())
  File "D:/python/workspace/YEDDA-master/YEDDA.py", line 381, in executeCursorCommand
    self.writeFile(self.fileName, content, cursor_index)
  File "D:/python/workspace/YEDDA-master/YEDDA.py", line 523, in writeFile
    self.autoLoadNewFile(new_name, newcursor_index)
  File "D:/python/workspace/YEDDA-master/YEDDA.py", line 542, in autoLoadNewFile
    text = self.readFile(fileName)
  File "D:/python/workspace/YEDDA-master/YEDDA.py", line 262, in readFile
    text = f.read()
  File "D:\python\Anaconda\envs\tenvf\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 0: invalid start byte
delete insert: 1.1
A

**Comment by Sweetjy** [comment]
导入中文文件时不会出错，但是标注就会出错，报错日志如下

**Comment by houruihui** [comment]
你好，我想问一下你是标注普通的实体还是特殊领域的实体？
